name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: build
        run: go build -v ./...
      - name: test
        run: go test -v ./...
  cover:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: cover tests
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: check coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: bump version
        uses: hennejg/github-tag-action@v4.1.jh1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}