name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: build
        run: go build -v ./...
  cover:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: cover tests
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: check coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
  version:
    runs-on: ubuntu-latest
    needs: cover
    permissions: write-all
    steps:
      - uses: actions/checkout@master
      - name: bump version
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          DEFAULT_BUMP: patch
          TAG_PREFIX: v
        