name: PR
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: build
        run: go build -v ./...
  cover:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
      - name: cover tests
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...
      - name: check coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml